0.2.0-rc1 - Address PR comments for #37
klaxit/hidden-secrets-gradle-plugin pull request #47
Opened 2021-10-29 10:49 UTC by valydia

@marius-m made a great job on #37  - just addressing the final comments...

2022-03-21 16:10 UTC, valydia commented
Hey folks! Is there any chance this PR could be reviewed / merged? I'd be happy to address any feedback on it 👍 ... cc @ben-j69

2022-03-23 09:18 UTC, ben-j69 commented
@valydia yes it is planned but we are very busy for the moment.

2022-04-15 14:21 UTC, ben-j69 requested changes
@valydia, thanks for the work. Can you rebase and adjust some last comments.

I have time allowed to close this improvement.

It will be merge and release in 0.2.0-rc1

2022-04-15 14:21 UTC, ben-j69 commented on src/main/kotlin/com/klaxit/hiddensecrets/HiddenSecretsPlugin.kt
> +        fun copyCppFiles(clean: Boolean) {
A parameter called `overwrite` would be clearer. And to not change too much the code and the actual behaviour a default value should be set. So the actual calls won't change
`        fun copyCppFiles(overwrite: Boolean = false) {}`

2022-04-15 14:21 UTC, ben-j69 commented on src/main/kotlin/com/klaxit/hiddensecrets/HiddenSecretsPlugin.kt
> +        fun copyKotlinFile(clean: Boolean) {
`Clean` is unclear here too.

2022-04-15 14:21 UTC, ben-j69 commented on src/main/kotlin/com/klaxit/hiddensecrets/HiddenSecretsPlugin.kt
> +         * Get properties file to hide secrets from
Get properties from the provided file

2022-04-15 14:21 UTC, ben-j69 commented on src/main/kotlin/com/klaxit/hiddensecrets/HiddenSecretsPlugin.kt
> +                    keyName = keyName,
Not need to repeat names and vars: 
`hideSecret(keyName, packageName, obfuscatedKey)`

2022-04-15 14:21 UTC, ben-j69 commented on src/main/kotlin/com/klaxit/hiddensecrets/HiddenSecretsPlugin.kt
> +                    hideSecret(
Not need to repeat names and vars: 
`hideSecret(keyName, packageName, obfuscatedKey)`

2022-04-15 19:28 UTC, valydia commented
Thanks for the review @ben-j69 ! I've addressed your comment in https://github.com/klaxit/hidden-secrets-gradle-plugin/pull/47/commits/a3cbe0462e136433f037b8295ef7c99541938bb7

2022-04-19 08:11 UTC, ben-j69 commented
Thanks @valydia , I will merge it in 0.2.0-rc1, test and adjust if necessary and then create a new release ;)

2022-04-19 08:11 UTC, ben-j69 approved these changes

2022-04-19 08:12 UTC, merged

2022-04-19 12:12 UTC, ben-j69 commented
Hello @valydia I made a mistake on rebase and I hade to manually copy the code to make a new commit here https://github.com/klaxit/hidden-secrets-gradle-plugin/pull/56 is it ok for you ? Not sure your name and @marius-m will appear on the repo.

If not can you create a new PR to master and I will recreate a 0.2.0

Thanks

2022-04-19 16:48 UTC, valydia commented
Hi @ben-j69 ! Thanks for letting me know! You can proceed with your new commit! Cheers